### PR TITLE
MAS19YE-9 MAS19YE-10 searchng for synonims and wiki

### PR DESCRIPTION
**Pull request by Posiadacz07**
Short script to search selected text

### CODE REVIEW

**Review by hXl3s — APPROVED** [review]

**Comment by Drutol** [comment]
What's up with synonym languages? Do you require some additional attribute for language?

**Comment by Posiadacz07** [comment]
There is searching for synonyms only in English. As far as I know there is no possibility to check language of the selected word. The only place will be test because of defined test language (English or Polish).

**Comment by Drutol** [comment]
So why are `PL` endpoints commented out?

**Comment by Posiadacz07** [comment]
As I wrote for this moment only English is available. This commented endpoints give us possibility to use Polish synonyms and Wikipedia in the future.

**Comment by Drutol** [comment]
Hence I asked whether you need some additional attributes to help with that.

**Comment by Posiadacz07** [comment]
Yes, I will be needed some additional attrubite to check which language is used in test. There should be some general language attribute not only in tests to deal with it in every part of application.

**Pull request merged**
